### ISSUE TITLE
Where's CDKDebugger.h file?

### ISSUE THREAD

**Issue by Hengyu** [mac-cain13/CoreDataKit#17]
Where's CDKDebugger.h file? Can't find it.

**Comment by mac-cain13** [comment]
There isn't a header file. Why are you looking for it? :)

**Comment by Hengyu** [comment]
Oh, Thanks:)

By the way, some of code is incompatible with swift 1.2. Maybe need an update.
For example, in swift 1.2 '@autoclosure' does not support enum.

**Comment by mac-cain13** [comment]
Jep! Will upgrade the project to Swift 1.2 today! :)

**Comment by Hengyu** [comment]
Great!
